version: "3.4"
services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
