spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/coffeewithme
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# Actuator
management:
  health:
    mongo:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  info:
    defaults:
      enabled: true
    git:
      mode: full

mongo:
  database:
    name: coffeewithme
    host: 127.0.0.1:27017
